### ISSUE TITLE
core_show_channels method return nil

### ISSUE THREAD

**Issue by ostapische** [emilianodellacasa/ruby-asterisk#16]
###### Environment:

```
~# ruby -v
ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]
~# gem -v
1.8.15
~# gem list -l ruby-asterisk
ruby-asterisk (0.1.0)
```
###### Code:

``` ruby
@ami = RubyAsterisk::AMI.new( "host", port )
@ami.login( "login", "password" )
core_show_channels = @ami.core_show_channels
```
###### Error:

```
can't convert nil into String
```
###### Trace:

```
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:34:in `concat_without_safety'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/string/output_safety.rb:34:in `<<'
/usr/lib/ruby/gems/1.8/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk.rb:146:in `execute'
/usr/lib/ruby/1.8/net/telnet.rb:598:in `waitfor'
/usr/lib/ruby/gems/1.8/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk.rb:145:in `execute'
/usr/lib/ruby/gems/1.8/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk.rb:49:in `core_show_channels'
```

I'm just change line [line 145 in lib/ruby-asterisk.rb](https://github.com/emilianodellacasa/ruby-asterisk/blob/master/lib/ruby-asterisk.rb#L145) from:

``` ruby
request.response_data << data
```

to:

``` ruby
request.response_data << data.to_s
```

And all works fine when `core_show_channels` returns `nil`, but I don't know why this error occurs.

**Comment by emilianodellacasa** [comment]
It seems ok to me, please submit it as a Pull Request. Thanks
