### ISSUE TITLE
no implicit conversion of Fixnum into String (TypeError)

### ISSUE THREAD

**Issue by havilchis** [emilianodellacasa/ruby-asterisk#26]
This is a example of my code:
```
require 'ruby-asterisk'

@ami = RubyAsterisk::AMI.new('192.XXX.X.XXX', 5038)
@ami.login('myusername', 'mypassword')

@ami.queue_add(1001, 'PJSIP/100', '')
```

When I executed it, got the following error:
```
/var/lib/gems/2.3.0/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk/request.rb:15:in `+': no implicit conversion of Fixnum into String (TypeError)
        from /var/lib/gems/2.3.0/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk/request.rb:15:in `block in commands'
        from /var/lib/gems/2.3.0/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk/request.rb:14:in `each'
        from /var/lib/gems/2.3.0/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk/request.rb:14:in `commands'
        from /var/lib/gems/2.3.0/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk.rb:139:in `execute'
        from /var/lib/gems/2.3.0/gems/ruby-asterisk-0.1.0/lib/ruby-asterisk.rb:93:in `queue_add'
        from prueba_asterisk.rb:42:in `<main>'
```

My quick fix was modify the  line number 15 in ruby-asterisk/request.rb
`commands<<key+": "+value+"\r\n" unless value.nil?`
by
`_commands<<"#{key.to_s}: #{value.to_s}\r\n" unless value.nil?`

now the fiile looks like this:
```
module RubyAsterisk
  class Request
    attr_accessor :action, :action_id, :parameters, :response_data

    def initialize(action,parameters={})
      self.action = action
      self.action_id = self.generate_action_id
      self.parameters = parameters
      self.response_data = ""
    end

    def commands
      _commands=["Action: "+self.action+"\r\n","ActionID: "+self.action_id+"\r\n"]
      self.parameters.each do |key,value|
        #commands<<key+": "+value+"\r\n" unless value.nil?
        _commands<<"#{key.to_s}: #{value.to_s}\r\n" unless value.nil?
      end
      _commands[_commands.length-1]<<"\r\n"
      _commands
    end 
```
Now the function is working fine

**Comment by emilianodellacasa** [comment]
It looks great to me, please submit a pull request to include it in the codebase for everyone.

Thanks!
